name: Auto PR to Staging

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for existing PR
        id: check-pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_COUNT=$(gh pr list --base staging --head develop --state open --json number --jq 'length')
          echo "pr_count=$PR_COUNT" >> $GITHUB_OUTPUT

      - name: Create PR to staging
        if: steps.check-pr.outputs.pr_count == '0'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --base staging \
            --head develop \
            --title "🚀 Deploy to Staging" \
            --body "## Automated PR from Develop to Staging

          This PR was automatically created when code was pushed to the \`develop\` branch.

          ### What to do next:
          1. Review the changes
          2. Run tests on staging environment
          3. Merge this PR to deploy to staging

          ### After merge:
          A release PR will be automatically created for production deployment.

          ---
          *Generated by GitHub Actions*"

      - name: PR already exists
        if: steps.check-pr.outputs.pr_count != '0'
        run: |
          echo "ℹ️ PR from develop to staging already exists. Skipping PR creation."
